---
name: Dispatch & Apply

on:
  workflow_call:
    inputs:
      terraform-version:
        description: "Version of terraform to use."
        required: false
        type: string
        default: 1.4.5
      auth-project-number:
        required: false
        type: string
        default: ""
      auth-project-name:
        required: false
        type: string
        default: ""
      dev-project-number:
        required: true
        type: string
      stage-project-number:
        required: true
        type: string
      prod-project-number:
        required: true
        type: string
      dev-project-name:
        required: true
        type: string
      stage-project-name:
        required: true
        type: string
      prod-project-name:
        required: true
        type: string
      dev-branches:
        required: true
        type: string
      stage-branches:
        required: true
        type: string
      prod-branches:
        required: true
        type: string

jobs:
  dispatch:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'terraform apply')
    runs-on: ubuntu-latest
    steps:

    - name: Get PR information
      run: |
        issue_number=$(jq -r ".issue.number" $GITHUB_EVENT_PATH)
        pr_url=$(jq -r ".issue.pull_request.url" $GITHUB_EVENT_PATH)
        base_ref=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $pr_url | jq -r ".base.ref")
        echo "BASE_REF=$base_ref" >> $GITHUB_ENV

    - name: Set env variables depending on the branch
      run: |
        if echo "${{ inputs.dev-branches }}" | grep -q "\b${{ env.BASE_REF }}\b"; then
          echo "SHOULD_APPLY=true" >> $GITHUB_ENV
        elif echo "${{ inputs.stage-branches }}" | grep -q "\b${{ env.BASE_REF }}\b"; then
          echo "SHOULD_APPLY=true" >> $GITHUB_ENV
        elif echo "${{ inputs.prod-branches }}" | grep -q "\b${{ env.BASE_REF }}\b"; then
          echo "SHOULD_APPLY=true" >> $GITHUB_ENV
        else
          echo "SHOULD_APPLY=false" >> $GITHUB_ENV
        fi

    - name: Run Dispatch
      if: env.SHOULD_APPLY == 'true'
      id: dispatch
      uses: ./terraform-dispatch
      with:
        passed_github_token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      apply: ${{ steps.dispatch.outputs.apply }}

  apply:
    if: ${{ needs.dispatch.outputs.apply == 'APPLY' }}
    needs: dispatch
    runs-on: ubuntu-latest
    steps:
    - name: Get Repository Name
      run: echo "repo_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Get PR information
      run: |
        issue_number=$(jq -r ".issue.number" $GITHUB_EVENT_PATH)
        pr_url=$(jq -r ".issue.pull_request.url" $GITHUB_EVENT_PATH)
        base_ref=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $pr_url | jq -r ".base.ref")
        echo "BASE_REF=$base_ref" >> $GITHUB_ENV

    - name: Set env variables depending on the branch
      run: |
        AUTH_PROJECT_NUMBER=""
        AUTH_PROJECT_NAME=""
        if echo "${{ inputs.dev-branches }}" | grep -q "\b${{ env.BASE_REF }}\b"; then
          if [ "${{ inputs.auth-project-number }}" != "" ] && [ "${{ inputs.auth-project-name }}" != "" ]; then
            AUTH_PROJECT_NUMBER=${{ inputs.auth-project-number }}
            AUTH_PROJECT_NAME=${{ inputs.auth-project-name }}
          else
            AUTH_PROJECT_NUMBER=${{ inputs.dev-project-number }}
            AUTH_PROJECT_NAME=${{ inputs.dev-project-name }}
          fi
          echo "PROJECT_NUBMER=${{ inputs.dev-project-number }}" >> $GITHUB_ENV
          echo "PROJECT_NAME=${{ inputs.dev-project-name }}" >> $GITHUB_ENV
          echo "WI_PROVIDER=projects/$AUTH_PROJECT_NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider" >> $GITHUB_ENV
          echo "SA_EMAIL=gha-${{ env.repo_name }}@$AUTH_PROJECT_NAME.iam.gserviceaccount.com" >> $GITHUB_ENV
          echo "TF_VARS_FILE=dev.tfvars" >> $GITHUB_ENV
          echo "SHOULD_APPLY=true" >> $GITHUB_ENV
        elif echo "${{ inputs.stage-branches }}" | grep -q "\b${{ env.BASE_REF }}\b"; then
          if [ "${{ inputs.auth-project-number }}" != "" ] && [ "${{ inputs.auth-project-name }}" != "" ]; then
            AUTH_PROJECT_NUMBER=${{ inputs.auth-project-number }}
            AUTH_PROJECT_NAME=${{ inputs.auth-project-name }}
          else
            AUTH_PROJECT_NUMBER=${{ inputs.stage-project-number }}
            AUTH_PROJECT_NAME=${{ inputs.stage-project-name }}
          fi
          echo "PROJECT_NUBMER=${{ inputs.stage-project-number }}" >> $GITHUB_ENV
          echo "PROJECT_NAME=${{ inputs.stage-project-name }}" >> $GITHUB_ENV
          echo "WI_PROVIDER=projects/$AUTH_PROJECT_NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider" >> $GITHUB_ENV
          echo "SA_EMAIL=gha-${{ env.repo_name }}@$AUTH_PROJECT_NAME.iam.gserviceaccount.com" >> $GITHUB_ENV
          echo "TF_VARS_FILE=stage.tfvars" >> $GITHUB_ENV
          echo "SHOULD_APPLY=true" >> $GITHUB_ENV
        elif echo "${{ inputs.prod-branches }}" | grep -q "\b${{ env.BASE_REF }}\b"; then
          if [ "${{ inputs.auth-project-number }}" != "" ] && [ "${{ inputs.auth-project-name }}" != "" ]; then
            AUTH_PROJECT_NUMBER=${{ inputs.auth-project-number }}
            AUTH_PROJECT_NAME=${{ inputs.auth-project-name }}
          else
            AUTH_PROJECT_NUMBER=${{ inputs.prod-project-number }}
            AUTH_PROJECT_NAME=${{ inputs.prod-project-name }}
          fi
          echo "PROJECT_NUBMER=${{ inputs.prod-project-number }}" >> $GITHUB_ENV
          echo "PROJECT_NAME=${{ inputs.prod-project-name }}" >> $GITHUB_ENV
          echo "WI_PROVIDER=projects/$AUTH_PROJECT_NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider" >> $GITHUB_ENV
          echo "SA_EMAIL=gha-${{ env.repo_name }}@$AUTH_PROJECT_NAME.iam.gserviceaccount.com" >> $GITHUB_ENV
          echo "TF_VARS_FILE=prod.tfvars" >> $GITHUB_ENV
          echo "SHOULD_APPLY=true" >> $GITHUB_ENV
        else
          echo "SHOULD_APPLY=false" >> $GITHUB_ENV
        fi

    - name: Run Apply
      if: env.SHOULD_APPLY == 'true'
      uses: ./terraform-apply
      with:
        passed_repository: ${{ github.repository }}
        passed_workload_identity_provider: ${{ env.WI_PROVIDER }}
        passed_service_account: ${{ env.SA_EMAIL }}
        passed_github_token: ${{ secrets.GITHUB_TOKEN }}
        passed_issue_number: ${{ github.event.issue.number }}
        passed_plan_bucket: "${{ env.PROJECT_NAME }}-tf-states"
        passed_ref: refs/pull/${{ github.event.issue.number }}/head
        generate_gcs_backend_config: true
        backend_bucket_name: "${{ env.PROJECT_NAME }}-tf-states"
        tf_version: ${{ inputs.terraform-version }}
